name: WakaTime Stat Update

on:
  schedule:
    # Запуск каждые 6 часов (можно чаще, но зачем?)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Кнопка для ручного запуска в табе Actions

jobs:
  update-readme:
    name: Update WakaTime Statistics
    runs-on: ubuntu-latest
    steps:
          - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: wakatime
          BLOCKS: "⏳"
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true # Это вместо того, что выдало ошибку. Он будет группировать редкие языки в "Other".
