name: WakaTime Stat Update

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Statistics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SYMBOL_VERSION: 2
          SHOW_TITLE: true
          SECTION_NAME: wakatime
          BLOCKS: "⏳"
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          SHOW_EDITS: false
          SHOW_LINES: false
          SHOW_PROFILE_VIEWS: false
          SHOW_PROJECTS: true
          SHOW_LANGUAGE_PER_REPO: false
